[indexer]
mode = "fsp"
rpc_concurrency = 20
batch_size = 1000
log_range = 30
new_block_check_millis = 1000
confirmations = 1
no_new_blocks_delay_warning = 60
history_epochs = 0

[logger]
level = "INFO"
file = "./logs/flare-cchain-indexer.log"
console = true

[chain]
node_url = "https://coston2-api.flare.network/ext/C/rpc"
chain_type = 1

[db]
host = "flare-ftso-mysql"
port = 3306
database = "flare_ftso_indexer"
username = "root"
password = "root"
log_queries = false
drop_table_at_start = false

[timeout]
backoff_max_elapsed_time_seconds = 300
rpc_timeout_millis = 8000
